server.port: 8090
#API GATEWAY CONFIG
spring:
  application.name: gateway
  cloud.gateway:
    discovery.locator:
      lower-case-service-id: true
      enabled: true
    routes:
    - id: crops-id
      uri: http://crops
      predicates:
        Path=/crops/**
    - id: user-id
      uri: http://users
      predicates:
        Path=/user/**
    - id: auth-id
      uri: http://auth
      predicates:
        Path=/auth/**
    - id: bill-id
      uri: http://bills
      predicates:
        Path=/bills/**
#EUREKA CLIENT CONFIG
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance.prefer-ip-address: true
